language: python

python:
  - "3.2"
  - "3.3"

install:
  - pip install -e .
  - pip install -r requirements/test.txt
  - pip install coveralls

script:
  - ./tests/runtests.sh

after_success:
    coveralls
