language: python

python:
  - "3.3"

install:
  - pip install -e .
  - pip install -r requirements/test.txt

script:
  - coverage run manage.py test

after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
