language: python

python:
  - "3.3"

install:
  - pip install -e .
  - pip install -r requirements/test.txt

script:
  - flake8 bakery --ignore='E122,E124,E125,E126,E128,E501,F403' --exclude="**/migrations/**,bakery/models.py"
  - coverage run manage.py test --settings=bakery.settings.test

after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
